import { useState, type FormEvent } from 'react';
import type { TeacherBossDetail } from '@lessonquest/contracts';
import type { LessonQuestApi } from '../api-client.js';

export function BossCampaignPanel({ api, organizationId, classId }: { readonly api: LessonQuestApi; readonly organizationId: string; readonly classId: string }) {
  const [detail,setDetail]=useState<TeacherBossDetail|null>(null); const [status,setStatus]=useState('공동 보스를 시작할 수 있습니다.');
  const create=(event:FormEvent)=>{event.preventDefault();const form=new FormData(event.currentTarget as HTMLFormElement);void api.createBossCampaign(organizationId,classId,{title:String(form.get('title')),period:{kind:'WEEKLY',weekStart:String(form.get('weekStart'))},targetHp:Number(form.get('targetHp')),policy:{amounts:{ANSWER_CORRECT:Number(form.get('correct')),ANSWER_RETRIED:Number(form.get('retried')),EXPERIENCE_COMPLETED:Number(form.get('completed'))}}}).then(value=>{setDetail(value);setStatus('공동 보스를 시작했습니다.');}).catch(()=>setStatus('공동 보스를 시작하지 못했습니다.'));};
  return <section className="panel boss-admin" aria-labelledby="boss-admin-title"><h2 id="boss-admin-title">반 공동 보스</h2>{detail===null?<form onSubmit={create}><label>보스 이름<input name="title" defaultValue="과학 공동 보스" maxLength={120} required /></label><label>주 시작일<input name="weekStart" type="date" defaultValue="2026-08-24" required /></label><label>목표 HP<input name="targetHp" type="number" min={60} max={60000} defaultValue={600} required /></label><label>첫 정답 기여<input name="correct" type="number" min={0} max={10000} defaultValue={2} /></label><label>재도전 정답 기여<input name="retried" type="number" min={0} max={10000} defaultValue={3} /></label><label>완료 기여<input name="completed" type="number" min={0} max={10000} defaultValue={5} /></label><button type="submit">보스 시작</button></form>:<><p>{detail.campaign.damage} / {detail.campaign.targetHp}</p><p>대기 {detail.projectionHealth.pending} · 실패 {detail.projectionHealth.failed}</p>{detail.contributions.map(row=><p key={row.studentId}>학생 ••{row.studentId.slice(-4)} · {row.damage}점 · {row.reasons.join(', ')}</p>)}</>}<p aria-live="polite">{status}</p></section>;
}
